### ISSUE TITLE
Exclude Rule

### ISSUE THREAD

**Issue by raz0rsedge1975** [yencarnacion/html4tree#1]
Hi there, 
thanks for this fine piece of software.
I'd like to ask if it's planned to be able to exclude filetypes from being listed in index.html.
Would be a nice feature.

Thx,
raz0r

**Comment by yencarnacion** [comment]
I have implemented a .html4ignore feature.  See the README.md file for details.

**Comment by raz0rsedge1975** [comment]
Oh that's very kind from you. Thank you very much.
